language: ruby
cache: bundler
sudo: required

rvm:
  - 2.4.6

env:
  global:
    - RECOVER_URL="http://localhost:5000"
    - SENDGRID_API_KEY=asdf

addons:
  postgresql: 9.6
  apt:
    update: true
    packages:
      - postgresql-server-dev-9.6
      - postgresql-9.6-postgis-2.4

before_install:
  - gem install rubygems-update && update_rubygems
  - yes | rvm @global do gem uninstall bundler --all
  - yes | rvm @global do gem install bundler -v 1.17.3 || true
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get install postgresql-contrib-9.6 postgis-2.4
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.6/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.6/main/pg_hba.conf'
  - sudo /etc/init.d/postgresql start 9.6
  - gem update --system
  - gem update bundler

before_script:
  - psql -U postgres -c "create extension postgis"
  - psql --version
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.sample config/secrets.yml

script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate
  - 'CODECLIMATE_REPO_TOKEN=xxx xvfb-run bundle exec rspec'
  - bundle exec rubocop

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: xxx
